tracker/Models/Tournament.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.TournamentScores = new HashSet<TournamentScore>();
        }
    
        public int TournamentID { get; set; }
        public string TournamentName { get; set; }
        public Nullable<int> LeagueID { get; set; }
        public Nullable<int> Rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentScore> TournamentScores { get; set; }
        public virtual League League { get; set; }
    }
}

tracker/ViewModels/RankingsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tracker.ViewModels
{
    public class RankingsViewModel
    {
        public int PlayerID { get; set; }
        [DisplayName("Player")]
        public string PlayerName { get; set; }// Player
        public int? OffenseRating { get; set; } 
        public int TournamentID { get; set; }
        public int TournamentScoresID { get; set; }

        public decimal OffenseRanking35 { get; set; }
        public decimal OffenseRanking28 { get; set; }
        public decimal OffenseRanking14 { get; set; }
        public decimal OffenseRanking7 { get; set; }

        public double Average20PointsFor { get; set; }
        public double Average20PointsAgainst { get; set; }
        public double Average20DefenseAgainst { get; set; }
        public double Grade { get; set; }

        public double Ladder { get; set; }

        public decimal DefensePowerRanking30 { get; set; }
    }
}

tracker/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using tracker.Models;
using tracker.ViewModels;
using PagedList;

namespace tracker.Controllers
{
    public class PlayersController : Controller
    {
        private trackerDBEntities db = new trackerDBEntities();

        // GET: Players
        public ActionResult Index()
        {
            var players = db.Players.Include(p => p.League).Include(p => p.Status).Where(p=> p.LeagueID == 2);
            return View(players.ToList());
        }

        // GET: Players/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }

            var playerStats = db.Players.Where(p => p.TournamentScores.Any(ts => ts.PlayerID == player.PlayerID));

            //return View(playerStats.ToList());

            List<PlayersViewModel> PlayersVW = new List<PlayersViewModel>();

            var playerDetails = (from p in db.Players
                join l in db.Leagues on p.LeagueID equals l.LeagueID
                join s in db.Status on p.StatusID equals s.StatusID
                join ts in db.TournamentScores on p.PlayerID equals ts.PlayerID
                join t in db.Tournaments on ts.TournamentID equals t.TournamentID
                where p.PlayerID == id
                select new
                {
                    p.PlayerID,
                    p.PlayerName,
                    p.ChatName,
                    s.StatusName,
                    l.LeagueName,
                    ts.Tournament,
                    ts.TournamentID,
                    ts.PointsFor,
                    ts.PointsAgainst,
                    t.TournamentName,
                    t.Rank
                });

            foreach (var item in playerDetails)
            {
                PlayersViewModel tvm = new PlayersViewModel();
                tvm.PlayerID = item.PlayerID;
                tvm.PlayerName = item.PlayerName;
                tvm.ChatName = item.ChatName;
                tvm.StatusName = item.StatusName;
                tvm.LeagueName = item.LeagueName;
                tvm.TournamentID = item.TournamentID.Value;
                tvm.TournamentName = item.TournamentName;
                tvm.Rank = item.Rank;
                tvm.PointsFor = item.PointsFor;
                tvm.PointsAgainst = item.PointsAgainst;

                foreach (var playerStat in playerStats)
                {
                    tvm.TotalPointsFor = playerStat.TournamentScores.Sum(x => x.PointsFor);
                    tvm.TotalPointsAgainst = playerStat.TournamentScores.Sum(x => x.PointsAgainst);
                    tvm.AveragePointsFor = playerStat.TournamentScores.Where(ts => ts.PointsFor != null).Average(x => Convert.ToDecimal(x.PointsFor));
                    tvm.AveragePointsAgainst = playerStat.TournamentScores.Where(ts => ts.PointsAgainst != null).Average(x => Convert.ToDecimal(x.PointsAgainst));

                    ViewBag.MissedDrives = playerStat.TournamentScores.Count(score => score.MissedDrives == true);
                }

                PlayersVW.Add(tvm);
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(PlayersVW.OrderByDescending(x => x.TournamentID).ToPagedList(pageNumber, pageSize));
        }

        // GET: Players/Create
        public ActionResult Create()
        {
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", 2);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "StatusName");
            return View();
        }

        // POST: Players/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlayerID,PlayerName,ChatName,StatusID,LeagueID,OffenseRating")] Player player)
        {
            if (ModelState.IsValid)
            {
                db.Players.Add(player);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", player.LeagueID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "StatusName", player.StatusID);
            return View(player);
        }

        // GET: Players/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", player.LeagueID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "StatusName", player.StatusID);
            return View(player);
        }

        // POST: Players/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlayerID,PlayerName,ChatName,StatusID,LeagueID,OffenseRating")] Player player)
        {
            if (ModelState.IsValid)
            {
                db.Entry(player).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", player.LeagueID);
            ViewBag.StatusID = new SelectList(db.Status, "StatusID", "StatusName", player.StatusID);
            return View(player);
        }

        // GET: Players/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = db.Players.Find(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: Players/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Player player = db.Players.Find(id);
            db.Players.Remove(player);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tracker/Controllers/TournamentScoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using tracker.Models;
using OfficeOpenXml;
using tracker.ViewModels;

namespace tracker.Controllers
{
    public class TournamentScoresController : Controller
    {
        private trackerDBEntities db = new trackerDBEntities();

        // GET: TournamentScores
        public ActionResult Index()
        {
            var tournamentScores = db.TournamentScores.Include(t => t.League).Where(t => t.LeagueID == 2).Include(t => t.Player).Where(t => t.Player.StatusID == 1).Include(t => t.Tournament).OrderBy(t => t.TournamentID);
            return View(tournamentScores.ToList().OrderByDescending(x => x.TournamentID));
        }

        // GET: TournamentScores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentScore tournamentScore = db.TournamentScores.Find(id);
            if (tournamentScore == null)
            {
                return HttpNotFound();
            }
            return View(tournamentScore);
        }

        // GET: TournamentScores/Create
        public ActionResult Create(int? id)
        {
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", 2);
            ViewBag.PlayerID = new SelectList(db.Players.Where(t => t.StatusID == 1).Include(t => t.League).Where(t => t.LeagueID == 2), "PlayerID", "PlayerName");
            ViewBag.TournamentID = new SelectList(db.Tournaments, "TournamentID", "TournamentName", id);
            ViewBag.MissedDrives = false;
            return View();
        }

        // POST: TournamentScores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TournamentScoresID,TournamentID,PlayerID,PointsFor,MissedDrives,PointsAgainst,LeagueID,DefenseAgainst")] TournamentScore tournamentScore)
        {
            if (ModelState.IsValid)
            {
                db.TournamentScores.Add(tournamentScore);
                db.SaveChanges();
                return RedirectToAction("Index", "Tournaments");
                //return RedirectToAction("Index");
            }

            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", tournamentScore.LeagueID);
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "PlayerName", tournamentScore.PlayerID);
            ViewBag.TournamentID = new SelectList(db.Tournaments, "TournamentID", "TournamentName", tournamentScore.TournamentID);
            return View(tournamentScore);
        }


        public ActionResult Upload()
        {
            return View();
        }
        // POST: TournamentScores/Upload
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(HttpPostedFileBase postedFile)
        {
            if (postedFile != null)
            {
                ExcelPackage package = new ExcelPackage(postedFile.InputStream);
                ExcelWorksheet worksheet = package.Workbook.Worksheets.FirstOrDefault();

                TournamentScore tournamentScore = new TournamentScore();
                
                int rowLength = worksheet.Dimension.End.Row;

                // plus 1 to avoid headers
                for (int rowIndex = worksheet.Dimension.Start.Row + 1; rowIndex <= rowLength; rowIndex++)
                {
                    var playerId = worksheet.Cells[rowIndex, 3].Value;
                    // don't include benched players or rows without a playerID
                    if (worksheet.Cells[rowIndex, 9].GetValue<int>() != 1 && playerId != null)
                    {
                        tournamentScore.TournamentID = worksheet.Cells[rowIndex, 1].GetValue<int>();
                        tournamentScore.LeagueID = worksheet.Cells[rowIndex, 2].GetValue<int>();
                        tournamentScore.PlayerID = worksheet.Cells[rowIndex, 3].GetValue<int>();
                        tournamentScore.PointsFor = worksheet.Cells[rowIndex, 5].GetValue<int>();
                        tournamentScore.PointsAgainst = worksheet.Cells[rowIndex, 6].GetValue<int>();
                        tournamentScore.MissedDrives = worksheet.Cells[rowIndex, 8].GetValue<bool>();
                        tournamentScore.DefenseAgainst = worksheet.Cells[rowIndex, 7].GetValue<int>();

                        db.TournamentScores.Add(tournamentScore);
                        db.SaveChanges();
                    }
                }

                //ViewBag.Message = "File uploaded successfully.";
            }

            return View();
        }

        // GET: TournamentScores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentScore tournamentScore = db.TournamentScores.Find(id);
            if (tournamentScore == null)
            {
                return HttpNotFound();
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", tournamentScore.LeagueID);
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "PlayerName", tournamentScore.PlayerID);
            ViewBag.TournamentID = new SelectList(db.Tournaments, "TournamentID", "TournamentName", tournamentScore.TournamentID);
            return View(tournamentScore);
        }

        // POST: TournamentScores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TournamentScoresID,TournamentID,PlayerID,PointsFor,MissedDrives,PointsAgainst,LeagueID,DefenseAgainst")] TournamentScore tournamentScore)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tournamentScore).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Tournaments", new {id=tournamentScore.TournamentID});
            }
            ViewBag.LeagueID = new SelectList(db.Leagues, "LeagueID", "LeagueName", tournamentScore.LeagueID);
            ViewBag.PlayerID = new SelectList(db.Players, "PlayerID", "PlayerName", tournamentScore.PlayerID);
            ViewBag.TournamentID = new SelectList(db.Tournaments, "TournamentID", "TournamentName", tournamentScore.TournamentID);
            return View(tournamentScore);
        }

        // GET: TournamentScores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentScore tournamentScore = db.TournamentScores.Find(id);
            if (tournamentScore == null)
            {
                return HttpNotFound();
            }
            return View(tournamentScore);
        }

        // POST: TournamentScores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TournamentScore tournamentScore = db.TournamentScores.Find(id);
            db.TournamentScores.Remove(tournamentScore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tracker/Views/Tournaments/Create.cshtml
@model tracker.Models.Tournament

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TournamentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TournamentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TournamentName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rank, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LeagueID, "LeagueID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LeagueID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LeagueID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-5">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
            <div class="col-md-5 text-right">
                @Html.ActionLink("Back to Tournaments", "Index")
            </div>
        </div>
    </div>
}

tracker/Views/Tournaments/Delete.cshtml
@model tracker.Models.Tournament

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TournamentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TournamentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.League.LeagueName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.League.LeagueName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tracker/Views/Tournaments/Details.cshtml
@model IEnumerable<tracker.ViewModels.TournamentsViewModel>

@{
    ViewBag.Title = "Relentless Ones 0.5 Tournament Details";
}

<div class="row">
    <div class="col-md-12">
        <p style="margin-top: 20px;">
            @Html.ActionLink("Back to Tournaments", "Index", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <h2>@Html.DisplayFor(model => model.FirstOrDefault().TournamentName) <small>details</small></h2>
        <p>@Html.DisplayFor(model => model.FirstOrDefault().Rank)</p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PlayerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PointsFor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PointsAgainst)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.OrderByDescending(x => x.TournamentID))
            {
                <tr class="details-row">
                    <td >
                        @Html.ActionLink(item.PlayerName, "Details", "Players", new { id = item.PlayerID }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PointsFor)
                        <p class="missed-drives @(item.MissedDrives.GetValueOrDefault() || item.PointsFor == null ? "" : "hidden") ">
                            Missed Drives
                        </p>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PointsAgainst)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "TournamentScores", new { id = item.TournamentScoresID }, new { @class = "btn btn-sm btn-default" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p style="margin-top: 20px;">
            @Html.ActionLink("Back to Tournaments", "Index", null, new { @class = "btn btn-default" })
        </p>
    </div>
</div>

tracker/Views/Tournaments/Edit.cshtml
@model tracker.Models.Tournament

@{
    ViewBag.Title = "Relentless Ones 0.5 Tournament Edit";
}

<div class="row">
    <div class="col-xs-12">
        <h2><small>@Html.DisplayFor(model => model.TournamentName)</small></h2>
        <h1>Edit Tournament<span class="pull-right">@Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })</span></h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.TournamentID)

                <div class="form-group">
                    @Html.LabelFor(model => model.TournamentName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TournamentName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TournamentName, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                    @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Rank, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Rank, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LeagueID, "League", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LeagueID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LeagueID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

tracker/Views/Tournaments/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<tracker.ViewModels.TournamentsViewModel>

@{
    ViewBag.Title = "Relentless Ones 0.5 Tournaments";
}

<div class="row">
    <div class="col-xs-12">
        <h2><small>Relentless Ones 0.5</small></h2>
        <h1>Tournaments <span class="pull-right">@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })</span></h1>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped">
            <tr>
                <th>
                   Rank
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().TournamentName)
                </th>
                <th class="text-center">
                    Outcome
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td style="vertical-align: middle;">
                        @Html.DisplayFor(modelItem => item.Rank)
                    </td>
                    <td style="vertical-align: middle;">
                        @Html.ActionLink(item.TournamentName, "Details", new { id = item.TournamentID })
                    </td>
                    <td class="text-center @(item.TotalPointsFor > item.TotalPointsAgainst ? "success" : "danger")" style="vertical-align: middle;">
                        @Html.DisplayFor(modelItem => item.TotalPointsFor) - @Html.DisplayFor(modelItem => item.TotalPointsAgainst)
                    </td>
                    <td class="text-right">
                        @Html.ActionLink("Add Scores", "Create", "TournamentScores", new { id = item.TournamentID }, new { @class = "btn btn-sm btn-success" })
                        @Html.ActionLink("Edit", "Edit", new { id = item.TournamentID }, new { @class = "btn btn-sm btn-default" })
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="col-xs-12">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
</div>